--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

terminal = "kitty"
fileManager = "nautilus"
browser = "librewolf"
browser_private = browser .. " --private-window"
discord = "discord --enable-features=UseOzonePlatform --ozone-platform=wayland"
codeapp = "code --enable-features=UseOzonePlatform --ozone-platform=wayland"
mail = browser .. " https://mail.proton.me"
cloud = browser .. " https://proton.me/drive"
aicompanion = browser .. " https://ai.local.lan"

--##################
--## KEYBINDINGS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(discord))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd(browser_private))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(codeapp))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(mail))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(cloud))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(aicompanion))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(terminal .. " --class clipse -e clipse"))

-- clipboard manager
hl.window_rule({
    match = {
        class = "^(clipse)$",
    },
    float = true,
    size = "622 652",
    stay_focused = true,
})

-- password manager (over browser)
hl.window_rule({
    match = {
        title = "^(vault\\.ruinformatique\\.ch_/)$",
    },
    float = true,
    size = "1100 800",
})

