--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("BROWSER", "librewolf")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XKBLAYOUT", "ch")
hl.env("XKB_DEFAULT_LAYOUT", "ch")
hl.env("XKBVARIANT", "fr")
hl.env("XKB_DEFAULT_VARIANT", "fr")

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

