-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.scripts/hypr-service.sh waybar waybar")
    hl.exec_cmd("~/.scripts/hypr-service.sh wallpaper $HOME/.scripts/hypr-live-wallpaper.sh")
    hl.exec_cmd("~/.scripts/hypr-service.sh hypridle hypridle")
    hl.exec_cmd("~/.scripts/hypr-service.sh polkit \"systemctl --user start hyprpolkitagent\"")
    hl.exec_cmd("~/.scripts/hypr-service.sh mako mako")
    hl.exec_cmd("~/.scripts/hypr-service.sh clipse \"clipse -listen\"")
    hl.exec_cmd("~/.scripts/hypr-service.sh nm-applet nm-applet")
    hl.exec_cmd("~/.scripts/hypr-service.sh swayosd swayosd-server")
    hl.exec_cmd("~/.scripts/hypr-service.sh blueman blueman-applet")
    hl.exec_cmd("~/.scripts/hypr-service.sh plugins $HOME/.config/hypr/loadHyprlandPlugins.sh")
    hl.exec_cmd("sleep 3 && ~/.scripts/hypr-service.sh waybar-peek $HOME/.scripts/waybar-peek.py")
    hl.exec_cmd("~/.scripts/hypr-service.sh animations \"$HOME/.scripts/hypr-animations.sh > /dev/null\"")
end)

