exec-once = ~/.scripts/startHyprService.sh waybar waybar
exec-once = ~/.scripts/startHyprService.sh wallpaper $HOME/.scripts/hyprLiveWallpaper.sh
exec-once = ~/.scripts/startHyprService.sh hypridle hypridle
exec-once = ~/.scripts/startHyprService.sh polkit "systemctl --user start hyprpolkitagent"
exec-once = ~/.scripts/startHyprService.sh mako mako
exec-once = ~/.scripts/startHyprService.sh clipse "clipse -listen"
exec-once = ~/.scripts/startHyprService.sh nm-applet nm-applet
exec-once = ~/.scripts/startHyprService.sh swayosd swayosd-server
exec-once = ~/.scripts/startHyprService.sh blueman blueman-applet
exec-once = ~/.scripts/startHyprService.sh keyring "/run/current-system/sw/bin/gnome-keyring-daemon --start --components=ssh"
exec-once = ~/.scripts/startHyprService.sh plugins $HOME/.config/hypr/loadHyprlandPlugins.sh
exec-once = ~/.scripts/startHyprService.sh waybar-peek $HOME/.scripts/waybar_peek.py
exec-once = ~/.scripts/startHyprService.sh animations "$HOME/.scripts/hyprCustomAnimations.sh > /dev/null"