exec-once = ~/.scripts/hypr-service.sh waybar waybar
exec-once = ~/.scripts/hypr-service.sh wallpaper $HOME/.scripts/hypr-live-wallpaper.sh
exec-once = ~/.scripts/hypr-service.sh hypridle hypridle
exec-once = ~/.scripts/hypr-service.sh polkit "systemctl --user start hyprpolkitagent"
exec-once = ~/.scripts/hypr-service.sh mako mako
exec-once = ~/.scripts/hypr-service.sh clipse "clipse -listen"
exec-once = ~/.scripts/hypr-service.sh nm-applet nm-applet
exec-once = ~/.scripts/hypr-service.sh swayosd swayosd-server
exec-once = ~/.scripts/hypr-service.sh blueman blueman-applet
exec-once = ~/.scripts/hypr-service.sh plugins $HOME/.config/hypr/loadHyprlandPlugins.sh
exec-once = ~/.scripts/hypr-service.sh waybar-peek $HOME/.scripts/waybar-peek.py
exec-once = ~/.scripts/hypr-service.sh animations "$HOME/.scripts/hypr-animations.sh > /dev/null"