--##################
--## KEYBINDINGS ###
--##################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local menu = "rofi -modi drun,run -show drun -show-icons"
local gotoscript = "bash ~/.scripts/goto.sh"

-- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- screenshots
hl.bind("print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

-- lock
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- Monocle mode (fullscreen)
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

-- shutdown
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("$terminal --class shutdown_confirm -e ~/.scripts/shutdown-confirm.sh"))

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("$fileManager"))
--bind = $mainMod, V, togglefloating,
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd(gotoscript))
--bind = $mainMod, P, pseudo, # dwindle
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.scripts/swayosd-wrapper.sh volume up"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.scripts/swayosd-wrapper.sh volume down"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.scripts/swayosd-wrapper.sh volume mute"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.scripts/swayosd-wrapper.sh brightness up"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.scripts/swayosd-wrapper.sh brightness down"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause && ~/.scripts/swayosd-wrapper.sh media play-pause"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous && ~/.scripts/swayosd-wrapper.sh media prev"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next && ~/.scripts/swayosd-wrapper.sh media next"))

-- Toggle HDR
hl.bind(mainMod .. " + ALT + B", hl.dsp.exec_cmd("~/.scripts/hypr-toggle-hdr.sh"))

-- Window rules
hl.window_rule({
    match = {
        class = "^(shutdown_confirm)$",
    },
    float = true,
    size = "300 100",
})

