-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
-- CONFIG FILES #
--###############

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- hyprlang2lua polyfills — runtime helpers reproducing
-- hyprlang behaviour the typed Lua API doesn't expose directly.

local function hl_source_glob(pattern)
    -- 'source = path/*.conf' had hyprlang glob and inline-expand the
    -- matches. require() can't glob, so we shell out to ls (matching
    -- the user's brace-expansion behaviour) and dofile each result.
    -- Paths with spaces or shell metacharacters in the directory
    -- portion will misparse; typical ~/.config/hypr/ layouts don't
    -- hit this. Swap to lfs.dir() or find -name if you need fancier.
    local p = io.popen("ls " .. pattern .. " 2>/dev/null")
    if not p then return end
    for f in p:lines() do
        local chunk, err = loadfile(f)
        if chunk then chunk()
        else io.stderr:write("hl_source_glob: " .. tostring(err) .. "\n") end
    end
    p:close()
end

-- Source: ~/.config/hypr/hyprland.d/*.conf (glob; resolved at runtime). Each matched .conf must be converted to .lua.
hl_source_glob("~/.config/hypr/hyprland.d/*.lua")
-- Source: ~/.config/hypr/hyprland.profiles.d/current/*.conf (glob; resolved at runtime). Each matched .conf must be converted to .lua.
hl_source_glob("~/.config/hypr/hyprland.profiles.d/current/*.lua")
