# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "uas" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2ff75c39-b6c8-4759-a603-e86259a6d52a";
    fsType = "ext4";
    options = [ "noatime" "discard" "data=ordered" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E805-FE1F";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [{
    device = "/dev/disk/by-uuid/5e272b4c-b9ca-4851-9867-2d3bcc420cdd";
  }];

  # Enable Windows disk access
  boot.supportedFilesystems = [ "ntfs" ];

  # NTFS filesystems
  fileSystems."/mnt/sata_1to" = {
    device = "/dev/disk/by-uuid/40D0F6D1D0F6CBE2";
    fsType = "ntfs3";
    options = [
      "noatime"
      "uid=1000"
      "gid=1000"
      "umask=0022"
      "async"
      "nofail"
    ];
  };

  fileSystems."/mnt/windows_1to" = {
    device = "/dev/disk/by-uuid/0A6EB9136EB8F891";
    fsType = "ntfs3";
    options = [
      "noatime"
      "windows_names"
      "async"
      "nofail"
    ];
  };

  fileSystems."/mnt/nvme_2to" = {
    device = "/dev/disk/by-uuid/71cb3e4b-0324-4750-902a-152733e1c7d0";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  # shares
  fileSystems."/mnt/shares/backups" = {
    device = "//big-nas-x/backups";
    fsType = "cifs";
    options = [
      "credentials=/etc/nixos/secrets/fs-backups-creds.env"
      "uid=1000"
      "gid=100"
      "dir_mode=0755"
      "file_mode=0644"
      "x-systemd.automount"
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Custom
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  services.xserver.enable = false;
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.xone.enable = true;

  hardware.nvidia = {
    modesetting.enable = true;
    open = true;
    gsp.enable = true;
    nvidiaSettings = true;
    powerManagement.enable = true;
    powerManagement.finegrained = false;
  
    package = config.boot.kernelPackages.nvidiaPackages.mkDriver {
      version = "610.57.04";

      sha256_64bit = "sha256-suk1xmuDuwDAyFe8jg7g/VLekoa0DJzB7sKafOfrEW0=";
      sha256_aarch64 = lib.fakeHash;
      openSha256 = "sha256-rQHOOOY4KL92Ww3KDwh+j4eGU7oNAH8LutZC5wmFnPo=";
      settingsSha256 = "sha256-ZEMo8I8Zc2Tq6RVDNYpAH+f094dUaZiBqO+5f6lIjRI=";
      persistencedSha256 = lib.fakeHash;
    };
  };

  boot.kernelParams = [
    "nvidia-drm.modeset=1"
    "amd_pstate=active"
    "processor.max_cstate=5"
  ];

  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;

  boot.loader.limine.secureBoot.enable = true;

  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
    "vm.max_map_count" = 1048576;
  };

  services.pipewire = {
    enable = true;

    pulse.enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    jack.enable = true;

    wireplumber = {
      enable = true;
      extraConfig = {
        disable-auto-port = {
          "monitor.alsa.rules" = [
            {
              matches = [
                {
                  "node.description" = "~.*XG32UCWMG.*";
                }
              ];
              actions = {
                update-props = {
                  "priority.session" = 3000;
                };
              };
            }
          ];
        };
      };
    };
  };

  services.pulseaudio.enable = false;

  # Enable NVIDIA Container Toolkit
  hardware.nvidia-container-toolkit.enable = true;

  services.udev.extraRules = ''
    # Enable keychron support
    KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="3434", MODE="0660", GROUP="input", TAG+="uaccess"
  '';



}