--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- SDR
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "desc:ASUSTek COMPUTER INC XG32UCWMG T7LMQS112894",
    mode = "3840x2160@240.02",
    position = "0x0",
    scale = "1",
    bitdepth = 10,
})

-- HDR
--monitor=desc:ASUSTek COMPUTER INC XG32UCWMG T7LMQS112894,3840x2160@240.02,0x0,1,bitdepth,10,cm,hdr
hl.monitor({
    output = "desc:ASUSTek COMPUTER INC VG27A R1LMQS086730",
    mode = "2560x1440@165",
    position = "3840x0",
    scale = "1",
})

--###################
hl.workspace_rule({
    workspace = "1",
    monitor = "desc:ASUSTek COMPUTER INC XG32UCWMG T7LMQS112894",
    default = true,
})

